name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5

      - name: Extract project
        run: |
          mkdir project
          unzip -q AutoBotSimulator-AndroidProject.zip -d project

      - name: Build APK
        run: |
          PROJECT_DIR=$(find project -type f \( -name settings.gradle -o -name settings.gradle.kts \) -print -quit | xargs dirname)
          cd "$PROJECT_DIR"
          gradle :app:assembleDebug --no-daemon       
          cp app/build/outputs/apk/debug/app-debug.apk "$GITHUB_WORKSPACE/app-debug.apk"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
         name: AutoBotSimulator-APK
         path: app-debug.apk
